/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cobamodul9;

import cobamodul9.dao.FolderDaoSQLite;
import cobamodul9.dao.PasswordStoreDaoSQLite;
import cobamodul9.dao.UserDaoSQLite;
import cobamodul9.entities.Folder;
import cobamodul9.entities.PasswordStore;
import cobamodul9.entities.UserData;
import cobamodul9.helpers.DBConnect;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        try (Connection conn = DBConnect.connect()) {
            UserDaoSQLite userDao = new UserDaoSQLite(conn);
            FolderDaoSQLite folderDao = new FolderDaoSQLite(conn);
            PasswordStoreDaoSQLite passwordDao = new PasswordStoreDaoSQLite(conn);

            // Tambah 2 data user
            int userId1 = userDao.register("riyani223", "099284", "riyani undana");
            int userId2 = userDao.register("butettt", "securepass", "butete lia");

            // Tambah 4 data folder
            int folderId1 = folderDao.createFolder("Social Media");
            int folderId2 = folderDao.createFolder("E-commerce");
            int folderId3 = folderDao.createFolder("Work");
            int folderId4 = folderDao.createFolder("Personal");

            // Tambah 5 data password untuk user pertama (userId1)
            addPassword(passwordDao, userId1, "Facebook", "riyani223", "099284", PasswordStore.CAT_WEBAPP, folderId1);
            addPassword(passwordDao, userId1, "Instagram", "riyani223", "099284", PasswordStore.CAT_MOBILEAPP, folderId1);
            addPassword(passwordDao, userId1, "Amazon", "riyani223", "099284", PasswordStore.CAT_WEBAPP, folderId2);
            addPassword(passwordDao, userId1, "Gmail", "riyani223", "099284", PasswordStore.CAT_OTHER, folderId3);
            addPassword(passwordDao, userId1, "Netflix", "riyani223", "099284", PasswordStore.CAT_MOBILEAPP, folderId4);

            // Tambah 5 data password untuk user kedua (userId2)
            addPassword(passwordDao, userId2, "Twitter", "butettt", "securepass", PasswordStore.CAT_WEBAPP, folderId1);
            addPassword(passwordDao, userId2, "TikTok", "butettt", "securepass", PasswordStore.CAT_MOBILEAPP, folderId1);
            addPassword(passwordDao, userId2, "eBay", "butettt", "securepass", PasswordStore.CAT_WEBAPP, folderId2);
            addPassword(passwordDao, userId2, "Outlook", "butettt", "securepass", PasswordStore.CAT_OTHER, folderId3);
            addPassword(passwordDao, userId2, "Spotify", "butettt", "securepass", PasswordStore.CAT_MOBILEAPP, folderId4);

            //  Tampilkan semua data password untuk user pertama (userId1)
            System.out.println("\nData Password untuk User Pertama:");
            UserData user1 = userDao.login("riyani223", "099284");
            if (user1 != null) {
                ArrayList<PasswordStore> passwords = passwordDao.listPassword(user1);
                for (PasswordStore pass : passwords) {
                    System.out.println("Nama Akun: " + pass.name);
                    System.out.println("Username: " + pass.username);
                    System.out.println("Category: " + pass.getCategory());
                    System.out.println("Folder: " + folderDao.getFolderNameById(pass.folder.id));
                    System.out.println("--------------------");
                }
            } else {
                System.out.println("User tidak ditemukan!");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private static void addPassword(PasswordStoreDaoSQLite passwordDao, int userId, String name, String username,
                                     String password, int category, int folderId) {
        Folder folder = new Folder(folderId, "");
        PasswordStore newPassword = new PasswordStore(name, username, password, category, folder);
        passwordDao.addPassword(newPassword, new UserData(userId, "", "", ""));
    }
}

